language: node_js
node_js:  
  - "node"

install: 
  - npm install

before_script: 
  - lerna bootstrap

script:
  - tsc && jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
